name: Rangefinder impact analysis
on: pull_request
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
      with:
        fetch-depth: 1

    - name: Set up Ruby
      uses: actions/setup-ruby@v1

    - name: list files
      run: |
        URL="https://api.github.com/repos/${GITHUB_REPOSITORY}/pulls/${{ github.event.pull_request.number }}/files"
        export FILES=$(curl -s -X GET -G $URL | jq -r '.[] | .filename')
        echo "::set-env name=FILES::$FILES"

    - name: Run analysis
      run: |
        gem install puppet-community-rangefinder
        mkdir output
        rangefinder ${{ env.FILES }} > results.md

#     - uses: actions/upload-artifact@v1
#       with:
#         name: results
#         path: output
    
#     - uses: actions/download-artifact@v1
#       with:
#         name: results
    
    - name: Post report
      uses: machine-learning-apps/pr-comment@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        path: results.md
